import type { Metadata } from "next";
import { Sen, Geist, Geist_Mono } from "next/font/google";
import { Providers } from "@/app/providers"
import Navbar from "@/components/navbar";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const senFont = Sen({
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Antarala: Jelajahi Indonesia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${senFont.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main>
          <Navbar />
          <Providers>{children}</Providers>
        </main>
      </body>
    </html >
  );
}
